### PR TITLE
bugfix: get_all_DBAdaptors() should return an empty list if the species name (alias) does not exist

### PR DESCRIPTION
**Pull request by muffato**
Otherwise it returns the list of all DBAdaptors ... (when -GROUP is not set)

### CODE REVIEW

**Comment by nerdstrike** [comment]
I fully expect there to be consequences for this change, but the change is valid.

**Comment by muffato** [comment]
I did run registy.t but only focused on the two tests and missed the error:
```
not ok 21 - no (unexpected) warnings (via done_testing)
#   Failed test 'no (unexpected) warnings (via done_testing)'
#   at modules/t/registry.t line 136.
1..21
```
I'll try to fix that

**Comment by muffato** [comment]
It looks like I need to test all the warning messages too. It doesn't hurt :)

**Comment by magaliruffier** [comment]
sorry, I am not sure I fully understand.
Are you planning to add some changes or is this good to go?

**Comment by muffato** [comment]
It's good to go

**Pull request merged**
