### PR TITLE
Extra parameters for the REST endpoint 'overlap/translation'. Will be…

### PR DESCRIPTION
**Pull request by ens-lgil**
… needed for a mapping to the PDB coordinates in a tool/feature using it

### CODE REVIEW

**Comment by ens-lgil** [comment]
I believe I will have to update the test on the ensembl-rest repo

**Comment by avullo** [comment]
Hi Laurent,
yes, but can you also add a relevant test to proteinFeature.t and/or proteinFeatureAdaptor.t if that's not too painful?

thanks

**Comment by ens-lgil** [comment]
@avullo, you don't have tests about the method 'summary_as_hash'.
Do you mean I need to create tests for this method ?

**Comment by avullo** [comment]
That would be ideal, I saw this an an opportunity to start covering this uncovered part of the API, especially considering coverage has, even marginally decreased. Feel free to do or not do that. It could be just testing the newly added fields.

**Comment by ens-lgil** [comment]
Ok, I just added few tests on "summary_as_hash"

**Comment by avullo** [comment]
Brilliant, well done!
Let's wait the tests then it goes in.

thanks a mil

**Pull request merged**
