### PR TITLE
Do not gzip checksum

### PR DESCRIPTION
**Pull request by ens-ma7**

### CODE REVIEW

**Comment by nerdstrike** [comment]
I can see why you would do this. I hope it doesn't upset any assumptions about copying all the gz files or similar.

**Comment by magaliruffier** [comment]
is '<' not for reading files, while '>' is for writing to them?

**Comment by ens-ma7** [comment]
Kieron, we do have other check related with the gz files which are taken care as well. In fact you just reminded me that i need to look at it :)

Magali, yeah you are right, its '>' i always make that stupid file handler mistake...doh! do i have to do another pull request or can you make the changes for me.

**Comment by magaliruffier** [comment]
You should be able to make the changes straight on the github interface, which updates the PR automatically

**Comment by ens-ma7** [comment]
ok i managed to find my way through github and made the new  change. let me know if there is anything wrong.
Thanks
Ridwan

**Comment by magaliruffier** [comment]
that seems fine to me
Have you had a chance to test it for this release's dumps?

**Comment by ens-ma7** [comment]
Has this been merged to your master/release branch because i cant seem to see my changes on the master copy of this file? Or am i losing it :)

**Comment by magaliruffier** [comment]
it has not been merged yet

**Pull request merged**
