### PR TITLE
Fixed fetch_all_by_Slice_and_external_dbname_link

### PR DESCRIPTION
**Pull request by simonbrent**
$self->get_DBEntryAdaptor() doesn't exist

### CODE REVIEW

**Comment by magaliruffier** [comment]
thanks for the fix, goes to show how much we've been using that method...

**Comment by simonbrent** [comment]
Yeah, well, I tried to use it because I wanted all genes with HGNC names, but even after fixing it looked like it would be MUCH slower than just fetching all genes and then grepping for $_->display_xref->dbname eq 'HGNC'

**Comment by magaliruffier** [comment]
do you need it slice by slice? or could you just use the 'list_gene_ids_by_external_db_id' directly?
either way, we'll look into the performance issues as well

**Comment by simonbrent** [comment]
list_gene_ids_by_external_db_id give back just a list of gene dbIDs, so I'd still have to get all the genes after that and check that their dbIDs are in that list, so the speed is about the same either way.

Also, I only want genes on 1-22, X, Y, MT, so I have to check that and throw the rest away.

**Comment by nerdstrike** [comment]
Seems sane. Thanks Simon

**Pull request merged**
