### PR TITLE
fix for VariationFeatures using a fake adaptor on circular slices

### PR DESCRIPTION
**Pull request by willmclaren**
Should work to fix @nicklangridge 's problems

### CODE REVIEW

**Comment by avullo** [comment]
I don't think you need to call $self->adaptor twice, suffice the call to the dbc submethod.

**Comment by nicklangridge** [comment]
Thanks Will.
Looks like the same check should be applied at this line https://github.com/Ensembl/ensembl/blob/release/82/modules/Bio/EnsEMBL/Feature.pm#L1145

**Comment by willmclaren** [comment]
I've update this PR with the suggested changes.

**Comment by magaliruffier** [comment]
thanks for the updates, looks fine now

**Comment by nicklangridge** [comment]
> I don't think you need to call $self->adaptor twice, suffice the call to the dbc submethod.

It turns out we do need the call to $self->adaptor

**Comment by nicklangridge** [comment]
Should I submit another PR?

**Comment by magaliruffier** [comment]
yes please
will you need this on release/83 branch as well?

**Comment by nicklangridge** [comment]
yes we will - do you want a PR on each branch?

**Comment by magaliruffier** [comment]
one will be fine, I'll just rebase the change

**Pull request merged**
