### PR TITLE
Feature/ubuntu 20

### PR DESCRIPTION
**Pull request by mira13**
## Description

The changes performed to make ensembl tests compatable with Ubuntu 20, Mysql 8
## Use case

SOme test are failing for Ubuntu_20 and mysql8, so it'a fix for them

## Benefits

It's a step towards new system

## Possible Drawbacks

Not observed
## Testing

_Have you added/modified unit tests to test the changes?_

Yes, they pass with new ensembl-test repository changes

_Have you run the entire test suite and no regression was detected?_

yes

### CODE REVIEW

**Comment by mira13** [comment]
@ens-bwalts This pr is essential now to keep master branch building fine

**Comment by mira13** [comment]
All ensembl tests will fail until this branch is merged. 

The matter is in compressed databases, i have changed them from binary to hex in ensembl, and the same - loading for that databases in ensembl-test changed to hex. So ensembl-test is merged, and ensembl is not.

**Review by magaliruffier — CHANGES_REQUESTED** [review]
Same comment as on https://github.com/Ensembl/ensembl/pull/516 regarding quoting either only 'rank' or all columns
Otherwise, the changes look fine to me, having an explicit order by in the methods makes a lot of sense

**Review by magaliruffier — APPROVED** [review]
changes look sensible

**Pull request merged**
