### PR TITLE
Update Feature.pm

### PR DESCRIPTION
**Pull request by ens-carlos**
Check if "slice" exists before calling "slice->is_circular()".

### CODE REVIEW

**Comment by nerdstrike** [comment]
How does a feature have coordinates if it lacks a slice?

**Comment by ens-carlos** [comment]
I had to add that check for the PDB protein features.

**Comment by nerdstrike** [comment]
So your features have a position but no frame of reference? Are they coordinates in protein residues?

**Comment by ens-carlos** [comment]
Yes, that's right. They are coordinates in protein residues.

**Comment by nerdstrike** [comment]
Resolved in person

**Pull request closed without merging**
