### PR TITLE
added multi-species database support

### PR DESCRIPTION
**Pull request by danstaines**

### CODE REVIEW

**Comment by nerdstrike** [comment]
You change a 1 to a 0 and then it's all fine?

**Comment by danstaines** [comment]
its binary baby!

**Comment by danstaines** [comment]
longer answer - this turns on the code which selects a list of 
species_id from meta to give you one DBAdaptor per species rather than 
one per db.

**Comment by nerdstrike** [comment]
Ok... then I have nothing to add.

**Comment by nerdstrike** [comment]
@premanand17 Best merge this in before branch tomorrow

**Pull request merged**
