### PR TITLE
ENSCORESW-2856: explicitly add DBD dependency

### PR DESCRIPTION
**Pull request by magaliruffier**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

_Using one or more sentences, describe in detail the proposed changes._
Import Devel::CheckLib with the other dependencies

## Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._
DBD::mysql has a dependency on Devel::CheckLib which is not correctly imported by most versions of cpan. This causes Travis to fail when setting up a new environment. The proposed fix imports the library explicitly

## Benefits

_If applicable, describe the advantages the changes will have._
All dependencies are correctly loaded in the tested environments. In particular, the test suite passes, removing noise when checking code changes.

## Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._
We add one more dependency that is not necessarily required for Ensembl and might disappear in the future.

## Testing

_Have you added/modified unit tests to test the changes?_
No changes required.

_If so, do the tests pass/fail?_
NA

_Have you run the entire test suite and no regression was detected?_
Yes

### CODE REVIEW

**Comment by lairdm** [comment]
Le sigh. Not my preferred solution, I wish DBD::mysql could address the dependency more elegantly. However reading the Checklib docs a little, the fact it's in Makefile.PL does make it difficult for them to address. Of course this will still have ripple effects on other repos that need DBD::mysql but not Ensembl (eg ensembl-hive), so this prairie dog will pop up a few more times before this is over.

**Comment by lairdm** [comment]
Oops, order might matter.

**Comment by wbazant** [comment]
I made an issue and now get all the emails! It looks like the DBD::mysql know what the problem is and will just fix it. Maybe you'd like to just wait for that? https://github.com/perl5-dbi/DBD-mysql/issues/263#issuecomment-420180077

**Comment by wbazant** [comment]
@lairdm it could be worse than "order matters" : https://github.com/miyagawa/cpanfile/issues/42 says these things are put in a hash and then the order is undefined :$

**Comment by magaliruffier** [comment]
I'm OK waiting until later today to see if that will be fixed on the cpan side of things
If it goes on for longer though, a temporary solution that allows us to check our code rather than external dependencies seems like the lesser of two evils

**Comment by magaliruffier** [comment]
The original error in the library has not been fixed, I can see 3 solutions:

- keep waiting for the fix. As all our test builds will fail in the mean time, we should probably not merge any more PRs until then
- include the dependency explicitly as in this PR. There might still be issues with the order in which dependencies are loaded
- fix the DBD::mysql version to 4.046

Any thoughts?

**Comment by magaliruffier** [comment]
I'll try the set version

**Pull request closed without merging**
