### PR TITLE
bugfix: not all users require a password

### PR DESCRIPTION
**Pull request by muffato**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Use case

I am not able to run `db-space.pl` with the ensro user, and I'd prefer not using ensadmin unless really needed

## Description

The script doesn't die any more if the password is not provided. It then only adds the `-p` option to the mysql command line if there is actually a password (`-p` alone makes mysql prompt for a password)

## Benefits

I can call  `db-space.pl` with the `ensro` to generate the disk usage reports

## Possible Drawbacks

The error message for someone running the script with `ensadmin` and no password will be different (it will come from . I don't expect anyone to be relying on that

## Testing

_Have you added/modified unit tests to test the changes?_

No, there were no tests on that script

_If so, do the tests pass/fail?_

N/A

_Have you run the entire test suite and no regression was detected?_

No.

### CODE REVIEW

**Comment by avullo** [comment]
Excellent, thanks for adhering to the template structure :+1: 

P.S. The "Requirements" is just communication to the puller, it can be discarded.

**Comment by muffato** [comment]
I have added another commit to make the script executable

**Comment by lairdm** [comment]
Approved.

**Comment by muffato** [comment]
Super, thank you !

**Pull request merged**
