### PR TITLE
Feature/alias chromosome

### PR DESCRIPTION
**Pull request by nwillhoft**
## Description

Draft pull request to add in a 'chromosome' alias feature to a coordinate system object. Please see JIRA ticket for more details: https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3021.

## Use case

Currently, a coordinate system named 'chromosome' may not exist in an Ensembl database, due to a change in sequence assembly formatting in databases created in the last few years. One example is the Atlantic Salmon database, which only contains a single coordinate system named 'primary_assembly'. If a user requests a chromosome slice object and there is no explicitly-named chromosome coordinate system in the query database, this new feature uses karyotype-based attributes in the database to identify a coordinate system to add an appropriate ('chromosome') alias to.

Registry details used in testing:

```
my $registry = 'Bio::EnsEMBL::Registry';
$registry->load_registry_from_db(
    -host    => 'mysql-ens-mirror-1.ebi.ac.uk',
    -user    => 'anonymous',
    -verbose => '0',
    -port    => 4240,
    -no_sql_schema_version_check => 1,
    -db_version => '101',
);
```

Atlantic Salmon use case details:

```
my $species = 'clupea_harengus';
my $group = 'core';
```

Slice adaptor / Slice example used:

```
my $slice_adaptor = $registry->get_adaptor( $species, $group, 'Slice' );
my $slice = $slice_adaptor->fetch_by_region('chromosome', '1');

# query slice for information about itself:
my $start = $slice->start();
my $end = $slice->end();

print "Name: ", $slice->coord_system()->name(), " ",
      $slice->seq_region_name, ", ",
      "alias: ", $slice->coord_system()->alias(), ", ",
      "start: $start, ",
      "end: $end.\n";
```

## Benefits

Where an Ensembl Core species database does not have coordinate system named chromosome, this code will create an alias to the appropriate coordinate system when a user requests a chromosome slice object, as long as the requested name has associated karyotype attributes.
 
## Possible Drawbacks

None I can think of.

## Testing

Have you added/modified unit tests to test the changes?

Yes. Added tests to `sliceAdaptor.t` and added a new test db for species parus_major. This species is a good example for testing because it does not have a chromosome coordinate system and has sequence regions where some have karyotype attributes and some do not.

If so, do the tests pass/fail?

On my local machine, the full test suite passes. On GitHub via the Travis-CI build, `sliceAdaptor.t` is failing and this seems to be because it cannot load the new parus_major test db (looking into this).

Have you run the entire test suite and no regression was detected?

To be confirmed.

### CODE REVIEW

**Comment by nwillhoft** [comment]
Have reverted to last commit relating directly to chromosome alias code. The 3 sets of automatic tests have passed. 
TODO: add in tests for chromosome alias feature.

**Comment by nwillhoft** [comment]
travis-ci checks are currently failing in `sliceAdaptor.t` when loading the new test db, `parus_major1`. As this passes when running locally, I believe this discrepancy be due to my local `MultiTestDB.conf` file which provides the test db connection info. However, it seems that this local file should not be added to the repo.

**Comment by mira13** [comment]
The error is about wrong syntax in mysql, please check your mysql version against server mysql version. Different versions have slightly different syntax

**Comment by nwillhoft** [comment]
Closing this PR because this task is being broken down into smaller PRs.

**Pull request closed without merging**
