### PR TITLE
store ontology term synonym xref separately from name

### PR DESCRIPTION
**Pull request by sarahhunt**
Allows searching by synonym via the API.

### CODE REVIEW

**Comment by sarahhunt** [comment]
Required for https://github.com/Ensembl/ensembl-production/pull/40

This leaves no way to access dbxrefs via the API - I can add one if it would be useful?

**Comment by magaliruffier** [comment]
I have not found any data where that field was actually populated, so you have any examples?
Given no one has needed it so far, I can survive without the API support for the time being
Otherwise, change looks fine

**Comment by sarahhunt** [comment]
GO terms often have an xref:

mysql> select * from synonym where term_id in (12,14,24);
+------------+---------+------------------------------------------------------------------+---------+
| synonym_id | term_id | name                                                             | type    |
+------------+---------+------------------------------------------------------------------+---------+
|          7 |      12 | "single-stranded DNA specific endodeoxyribonuclease activity" [] | RELATED |
|          8 |      12 | "ssDNA-specific endodeoxyribonuclease activity" [GOC:mah]        | RELATED |
|         10 |      14 | "lactase-phlorizin hydrolase activity" [EC:3.2.1.108]            | BROAD   |
|         11 |      14 | "lactose galactohydrolase activity" [EC:3.2.1.108]               | EXACT   |
|         29 |      24 | "50S ribosomal subunit assembly" [GOC:mah]                       | NARROW  |
|         30 |      24 | "60S ribosomal subunit assembly" [GOC:mah]                       | NARROW  |
+------------+---------+------------------------------------------------------------------+---------+

**Comment by lairdm** [comment]
Potentially silly question, are there downstream implications of this, how that new column will be loaded and accessed?

**Comment by sarahhunt** [comment]
@lairdm - there is a PR to update the loader : Ensembl/ensembl-production#40 and as discussed, there is now no way to extract dbxrefs, where present, via the API - happy to add one.

**Comment by magaliruffier** [comment]
bioperl is currently down, so all test suites fail
We're going to wait until Monday to see if it is resolved before taking new changes in

**Comment by lairdm** [comment]
Bioperl fixed, merging.

**Pull request merged**
