### PR TITLE
making seq_region name longer

### PR DESCRIPTION
**Pull request by gnaamati**
I want to alter seq_region_name to VARCHAR(255)

### CODE REVIEW

**Comment by magaliruffier** [comment]
The table.sql file should contain both the schema change and the patch identifier in the meta table. This insures a newly created database is identical to a patched one.
Can you please update accordingly?

**Comment by gnaamati** [comment]
Thanks for the comment.
I added the patch identifier in the meta table.

**Comment by magaliruffier** [comment]
sorry, patch file format is not picked up by the test, it should be patch_87_88_b.sql instead of patch_87_88.b.sql
Can you please change the file name this time round, and I'll update the test to allow more combination.

**Comment by gnaamati** [comment]
Sorry, my mistake, I updated it to patch_87_88_b.sql. 
Thanks for your patience with my first patch :)

**Comment by magaliruffier** [comment]
Success! Looks good to go ;-)

**Comment by gnaamati** [comment]
Great! 
Now it just needs to be updated in Compara, Variation and Funcgene....
At least the pull requests are all ready :)

**Pull request merged**
