### PR TITLE
Feature/biotype update to keep legacy biotype()

### PR DESCRIPTION
**Pull request by tgrego**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

_One or more sentences describing in detail the proposed changes._

Recent addition of Biotype objects used the old biotype method in gene and transcript.
This proven not to be 100% backwards compatible, so this is to include legacy biotype() dealing with the biotype name string, together with new get_Biotype and set_Biotype methods that deal with biotype objects.

## Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._

`to_json($gene->biotype)` would refuse to do it's job because $gene->biotype was returning an object, even though that object would behave as a string if to_json would make the effort to try it...
Now we bring $gene->biotype back to being a real string, and provide new methods to deal with objects.

## Benefits

Backwards compatibility

## Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._

Might have missed something

## Testing

_Have you added/modified unit tests to test the changes?_

Yes.

_If so, do the tests pass/fail?_

Pass, of course.

_Have you run the entire test suite and no regression was detected?_

Yes.

### CODE REVIEW

**Comment by nerdstrike** [comment]
Looks ok, are you expecting to make more changes?

**Comment by tgrego** [comment]
yes, I pushed just now a required schema_version check.

**Comment by magaliruffier** [comment]
I can confirm that the backwards compatibility tests I've executed are now working

**Comment by lairdm** [comment]
Did I miss it, is there a test for this fallback functionality?

**Comment by magaliruffier** [comment]
The test I ran locally is to call biotype on a database that is on schema 92 or older. Not sure how this could be integrated in the test suite, as we typically assume schema and API version are in sync

**Comment by lairdm** [comment]
Ahh, I see, $gene->biotype is testing in the unchanged sections still, that's what I was getting at. Alright, good to go.

**Pull request merged**
