### PR TITLE
New test database (Parus major)

### PR DESCRIPTION
**Pull request by nwillhoft**
## Description

Added a new test db for species Parus major. This species is a good example for testing the new chromosome alias feature because it has a single 'primary_assembly' coordinate system and has sequence regions where some have karyotype attributes and some do not.

## Use case

The use case of this test db is to test the new chromosome alias feature. To test the feature properly, we need a database with no chromosome coordinate system, and sequence regions with and without karyotype attributes. These data are captured in the Parus major core database.
 
## Benefits

Provide data to test the new chromosome alias feature.

## Possible Drawbacks

None I can think of.

## Testing

_Have you added/modified unit tests to test the changes?_

Not yet.

_Have you run the entire test suite and no regression was detected?_

Tests in the Travis-CI build all pass.

### CODE REVIEW

**Review by magaliruffier — APPROVED** [review]
The test data added is small enough that it does not negatively impact git size
gitlab has been having issues over the past few days, if Travis runs fine it's probably OK

**Review by ens-bwalts — APPROVED** [review]
Looks complete for testing chromosome-karyotype aliasing

**Comment by nwillhoft** [comment]
@magaliruffier @ens-bwalts Would it be ok for me to go ahead and merge this pull request with master using 'Create a merge commit'?

**Comment by ens-bwalts** [comment]
Yes, we're ready to merge this. As it has been approved by two reviewers, you can merge this yourself, and the "create a merge commit" option is indeed the appropriate one to use.

**Pull request merged**
