### PR TITLE
Update release/software version to 108

### PR DESCRIPTION
**Pull request by nwillhoft**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

As part of Core Release Activities 1 and 2:
- update the software and schema release versions from 107 to 108
- patch the test databases to 108, including any schema changes

## Use case

The software and schema release versions on the master branch of this repo require updating for the subsequent release (i.e. 108).

## Benefits

N/A

## Possible Drawbacks

N/A

## Testing

_Have you added/modified unit tests to test the changes?_

No.

_If so, do the tests pass/fail?_

I believe the current tests are failing because the release version number has been updated to 108, and tests are still expecting 107.

_Have you run the entire test suite and no regression was detected?_

### CODE REVIEW

**Review by TamyNab — CHANGES_REQUESTED** [review]
Hey Natalie. All looks good except that sql/table.sql files needs to be updated with the release bump as well.

**Review by TamaraNaboulsi — CHANGES_REQUESTED** [review]
So sorry! Was signed in with my personal account by mistake. Please disregard that comment.

sql/table.sql needs updating.

**Review by sgiorgetti — APPROVED** [review]
All files / changes look good

**Review by TamaraNaboulsi — APPROVED** [review]
Looks good.

**Pull request merged**
