### PR TITLE
Patching multi/compara test DB (missed by previous patching attempt)

### PR DESCRIPTION
**Pull request by TamaraNaboulsi**
## Description

Patching the multi/compara test DB, that was missed in a previous patching attempt. Changes for other DBs are in PR #552

### CODE REVIEW

**Review by mira13 — APPROVED** [review]
patching dbs

**Review by nwillhoft — COMMENTED** [review]
Changes observed in this PR:
- the `dnafrag_alt_region` table has been added to MySQL and SQLite schemas.
- schema version has been updated from 104 to 105
- unsigned has been added to a number of attributes
- some attributes of type integer have been changed to tinyint/smallint

Just wanted to check that all of these attribute changes have been approved by Compara?

**Comment by TamaraNaboulsi** [comment]
> 
> 
> Changes observed in this PR:
> 
>     * the `dnafrag_alt_region` table has been added to MySQL and SQLite schemas.
> 
>     * schema version has been updated from 104 to 105
> 
>     * unsigned has been added to a number of attributes
> 
>     * some attributes of type integer have been changed to tinyint/smallint
> 
> 
> Just wanted to check that all of these attribute changes have been approved by Compara?

The patch_test_databases.pl added these changes based on the patch_103_104_b.sql and patch_103_04_c.sql which it went through before using patch_104_105_a.sql. The script used a local compara repo cloned from master, which had the patch files. Let me know if anything in this procedure sounds wrong.

I have not contacted anyone from Compara regarding this. Is there a specific person I should get in contact with?

**Comment by nwillhoft** [comment]
Thanks a lot for the explanation, that makes a lot of sense that the changes to the schema attribute types have come from the updated patch files. Sorry for my misunderstanding, this all sounds great.

**Review by nwillhoft — APPROVED** [review]
All the changes look good and the build checks pass.

**Pull request merged**
