### PR TITLE
ensembl-3610 Adding a slice object to Region Report

### PR DESCRIPTION
**Pull request by jkhobova**

### CODE REVIEW

**Comment by avullo** [comment]
Many thanks,

looks all right to me, perhaps you want to merge against master as well?

cheers,

Alessandro

**Comment by jkhobova** [comment]
Many thanks for merging!
I've created another pull request for master.
Is it visible?

Thanks,
Julia

**Comment by avullo** [comment]
On 12/02/15 09:34, jkhobova wrote:
> Many thanks for merging!
> I've created another pull request for master.
> Is it visible?

Mhhh ... not yet, waiting for that to appear

thanks!

Alessandro

**Comment by jkhobova** [comment]
https://github.com/Ensembl/ensembl/pull/53
Thank you!

**Pull request merged**
