### PR TITLE
Added throw if features array is empty and moved checks to the top.

### PR DESCRIPTION
**Pull request by ens-carlos**

### CODE REVIEW

**Comment by avullo** [comment]
You don't have to close, only to wait for us to merge the request, unless you have an alternative reason to do so.

**Comment by ens-carlos** [comment]
Sorry, I thought it had already been merged.

**Comment by avullo** [comment]
Ok, sorry but you have to go through the process again. I cannot reopen the PR as you've deleted the source repo.

**Comment by ens-carlos** [comment]
Oh no, sorry about that! I'll do it again.

Cheers,
Carlos

**Pull request closed without merging**
