### PR TITLE
Return all adaptors in the registry in get_all_DBAdaptors if no args supplied

### PR DESCRIPTION
**Pull request by Zhicheng-Liu**
The changes included in this PR are the same as those in the PR #194 . I cherry picked all the commits from there.

I thought it would be good for these changes to go into release/88 too.

### CODE REVIEW

**Comment by magaliruffier** [comment]
are you planning to push those changes to the live webservers?
if so, I can't see any objection

**Comment by Zhicheng-Liu** [comment]
Yes, that was the aim.

**Comment by avullo** [comment]
And so be it, thanks.

**Comment by Zhicheng-Liu** [comment]
Thank you all!

**Pull request merged**
