### PR TITLE
Feature 83/strain slice tests

### PR DESCRIPTION
**Pull request by at7**
Added unit tests for StrainSlice module. I needed to add new mouse core and variation test databases for testing the StrainSlice module.

### CODE REVIEW

**Comment by nerdstrike** [comment]
Great, we can merge it

**Comment by magaliruffier** [comment]
more tests, thank you!
I guess there is still the plan to move this to ensembl-variation?

**Comment by at7** [comment]
Yes, the plan is to move the code to the variation API for release/84.

**Comment by magaliruffier** [comment]
perfect :-)

**Pull request merged**
