### PR TITLE
Feature 83/unit tests

### PR DESCRIPTION
**Pull request by at7**
I have added tests for the StrainSlice module. I created new variation and core test databases for mouse.

### CODE REVIEW

**Comment by nerdstrike** [comment]
Fair enough.

**Comment by nerdstrike** [comment]
Although please fix the tests. Travis is complaining

**Comment by at7** [comment]
I committed a change to the variation API to modify the query if the driver is SQLite. Could you please rerun the last Travis build? It should pick up the change in the variation API. Thank you

**Comment by nerdstrike** [comment]
Tests are passing, but coveralls coverage claims to have dropped hugely. I can't quite see how you've managed to knock 8% off.

**Comment by at7** [comment]
I'm going to close this pull request, clean up the commit history and create a new pull request.

**Pull request closed without merging**
