### PR TITLE
Master

### PR DESCRIPTION
**Pull request by khowe**

### CODE REVIEW

**Comment by magaliruffier** [comment]
thanks for the fix on the array express parser
the rest is wormbase specific, so you've probably tested it better than us ;-)
changes can go in as far as I'm concerned

**Comment by avullo** [comment]
I've seen you've added the method gene_description_sources but can't find it called in your commits.

**Comment by magaliruffier** [comment]
the gene_description_sources method is called in the DisplayXrefs module, but it can be overwritten by species-specific mappers

**Comment by avullo** [comment]
I see, thanks.

**Pull request merged**
