### PR TITLE
Import deprecate method

### PR DESCRIPTION
**Pull request by at7**

### CODE REVIEW

**Comment by avullo** [comment]
Should be ok, thanks.

**Comment by at7** [comment]
return Variation::StrainSlice. We probably want to get rid of this as well in the future? For now it avoids the StrainSlice module in the core API and uses the new one in the variation API.

**Comment by at7** [comment]
I try to move this into the variation API now and remove the dependency.

**Comment by at7** [comment]
OK. I moved get_by_strain to the variation API.

**Comment by magaliruffier** [comment]
thank you

**Pull request merged**
