### PR TITLE
Feature/xref standardisation

### PR DESCRIPTION
**Pull request by magaliruffier**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/master/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

The list of sources used for gene naming and gene description has been consolidated in a single place and used for most vertebrate species. This removes the need to maintain multiple lists for different species with the risk of them being out of sync.
Additionally, when multiple choices are available, a re-ordering has been applied to increase the chances of making the same choice when the pipeline is re-run

## Use case

_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._
We have genes where the name and the description are different, because different sources were used for each. This is confusing users. We also have cases where the same gene has a different name from one release to another, because there are two choices and one is arbitrarily chosen each time

## Benefits

_If applicable, describe the advantages the changes will have._
More consistency in the xref assignment, less queries from users, easier explanation of the name assignment strategy

## Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._
None that I can see

## Testing

_Have you added/modified unit tests to test the changes?_
no test cases, but the xref pipeline has been run on a large number of species to check the results

_If so, do the tests pass/fail?_
the pipeline runs fine and produces consistent results on the species it was tested on

_Have you run the entire test suite and no regression was detected?_
NA

### CODE REVIEW

**Comment by magaliruffier** [comment]
the gene_display_xref_sources method returns a reference array and a hash
the gene_description_sources method used to return a reference array and now returns a reference array and a hash
the hash is the second argument and is therefore ignored as not expected
this also means that if we want to add an ignore_list (badly named list as it is in fact a hash) for the gene_display_xref_sources, the argument is already provided

**Comment by ens-bwalts** [comment]
It looks to me like gene_description_sources used to return an actual array, not a reference array, which is what `@precedence` is expecting - there's no dereferencing.

**Comment by magaliruffier** [comment]
That's a fair point, let me have a look

**Comment by magaliruffier** [comment]
That was a good spot, I have changed the return type and was able to test it on our favourite xenopus example, ENSXETG00000034365
it now gets both display_xref and description from the same NCBIGene xref

**Review by ameya1981 — APPROVED** [review]
Approved after the change in return type for sub gene_description_sources

**Review by ens-bwalts — APPROVED** [review]

**Pull request merged**
