### PR TITLE
store version for ontology

### PR DESCRIPTION
**Pull request by sarahhunt**
We need to be able to track the versions of the ontologies used in each release. This updates the schema, API and test files.

### CODE REVIEW

**Comment by nerdstrike** [comment]
I suppose this should have been in there from the start. Code looks fine, and I see you've modified load_OBO_file.pl too!

**Comment by nerdstrike** [comment]
Bad luck, you missed the sqlite table defs.

**Comment by sarahhunt** [comment]
Yes - I'm told up to 10 terms can be deprecated a month from one of the ontologies we use, so it's essential to know which we are using.

**Comment by magaliruffier** [comment]
neat and tidy, thanks

**Pull request merged**
