### PR TITLE
Fix for sub_Slice when slice->start is <1

### PR DESCRIPTION
**Pull request by willmclaren**
If a slice has start<1, then it is valid to request an end that is
&gt; slice->end as long as it is <=slice->length, since sub_Slice args
are relative to the original slice.

Please do correct me if I'm wrong here! I am thoroughly confused by the concept of slices with start<1 to begin with :-)

### CODE REVIEW

**Comment by magaliruffier** [comment]
the strainSlice tests are failing on this change, might need to check what is happening there

**Comment by magaliruffier** [comment]
is there a plan to fix this PR or should I just close it until Anja's changes come in?

**Comment by willmclaren** [comment]
Will take a look. Might as well fix it here, at least then we will know where it's going to break when Anja moves the tests :-)

**Comment by willmclaren** [comment]
All fixed now

**Comment by magaliruffier** [comment]
Travis is happy now, thanks

**Comment by nerdstrike** [comment]
We should really get rid of all the return undefs. One day they'll bite someone.

**Pull request merged**
