### PR TITLE
patch for seq_region

### PR DESCRIPTION
**Pull request by gnaamati**
Adding a patch to make seq_region name longer

### CODE REVIEW

**Comment by lairdm** [comment]
You gotta do what you gotta do.

**Comment by gnaamati** [comment]
Sometimes you just have no choice.

**Comment by james-monkeyshines** [comment]
Presumably you don't really want this on the release/87 branch though?

**Comment by gnaamati** [comment]
Good point, will do a pull request on the master branch.
Thanks.

**Comment by james-monkeyshines** [comment]
It's probably also a good idea to update the tables.sql file with this change.

**Comment by gnaamati** [comment]
Done.

**Pull request closed without merging**
