### PR TITLE
Release/95

### PR DESCRIPTION
**Pull request by thomasmaurel**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
    - do not modify code without testing for regression
    - provide simple unit tests to test the changes
    - if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#updating-the-schema)
    - the PR must not fail unit testing

## Description

New schema patch to update the Vertebrates species.division meta key from "Ensembl" to "EnsemblVertebrates" for consistency. This has been declared by Magali here: https://www.ebi.ac.uk/panda/jira/browse/ENSINT-104.
Magali was supposed to create this patch before going in holiday but she ran out of time.

## Use case

This is for consistency across all the divisions. It was approved by Group leaders for 95 as seen here: https://www.ebi.ac.uk/panda/jira/browse/ENSINT-104.

## Benefits

_If applicable, describe the advantages the changes will have._

## Possible Drawbacks

_If applicable, describe any possible undesirable consequence of the changes._

## Testing

I tested the schema patch. I manually ran the Travis tests locally but got errors not related to my changes...

### CODE REVIEW

**Comment by thomasmaurel** [comment]
Opps sorry, there was a typo in table.sql and one of Travis test had a typo in the division name (not my fault ;-) ).

**Comment by thomasmaurel** [comment]
Apologies, I didn't realised that the Species.division was missing for human test database on purpose as it's added by the metaContainer test...

**Comment by thomasmaurel** [comment]
@mkszuba: I think you forgot to update the Compara test database to 95. I can have a look since I am updating the Travis tests...

**Comment by mkszuba** [comment]
And thanks for pointing out the missing Compara patches! This is what happens when one forgets to run 'git fetch' on ensembl-compara and ensembl-variation before running the patcher :-)

**Comment by thomasmaurel** [comment]
@mkszuba: Yes, it turned out to be pretty ugly... 
Sounds like a plan. Thanks for helping out with the Travis test.

**Pull request closed without merging**
